name: angel3_container_generator
version: 8.5.0
description: Codegen support for using pkg:reflectable with pkg:angel3_container.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/angel/tree/master/packages/container/container_generator
resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'
dependencies:
  angel3_container: ^8.4.0
  reflectable: ^5.0.0
dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^3.5.0
  test: ^1.24.0
  lints: ^6.0.0
